load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_library(
    name = "cos_similarity",
    srcs = ["cos_similarity.cc"],
    hdrs = ["cos_similarity.h"],
    deps = [
        "@opencv_3_4_3_linux_x86_64_precompiled//:core",
        "@eigen"
    ]
)

